import { normalizeVideoLesson, type VideoLessonMetadata, type VideoLessonScene } from "../lib/video-lessons/videoLessonTypes";
import type { VideoLessonLayoutId } from "../lib/video-lessons/videoLessonLayouts";

const scenes: Record<"definition" | "process" | "timeline" | "patient-scenario" | "quiz" | "avatar-intro" | "example" | "recap" | "avatar-outro", Partial<VideoLessonScene>> = {
  definition: { layoutId: "definition", icon: "clipboard", title: "Deductible", body: "The amount a patient pays before insurance begins contributing.", bullets: ["Patient responsibility", "Usually resets annually", "Confirm before estimating"], narrationScript: "A deductible is the amount a patient pays before insurance begins contributing." },
  process: { layoutId: "process", icon: "clipboard", title: "Insurance Verification", body: "Follow a consistent workflow before discussing coverage.", processSteps: [{ title: "Collect", description: "Gather patient information", icon: "clipboard" }, { title: "Verify", description: "Confirm active coverage", icon: "checklist" }, { title: "Call", description: "Clarify plan details", icon: "phone" }, { title: "Document", description: "Record the result", icon: "clipboard" }], narrationScript: "Collect, verify, call when needed, and document the result." },
  timeline: { layoutId: "timeline", icon: "calendar", title: "Waiting Period Timeline", body: "Track when benefits become available.", timelineMilestones: [{ label: "Enrollment", duration: "Day 1", description: "Coverage starts" }, { label: "Waiting period", duration: "6 months", description: "Benefits pending" }, { label: "Eligible", duration: "Month 7", description: "Benefits available" }], narrationScript: "Track enrollment, the waiting period, and the eligibility date." },
  "patient-scenario": { layoutId: "patient-scenario", icon: "patient", title: "Patient Scenario", patientQuote: "My insurance says everything is covered.", body: "The patient expects no out-of-pocket cost.", discussionPrompt: "How would you clarify their benefits?", recommendedResponse: "Explain estimates, deductible, coinsurance, and plan limitations.", narrationScript: "A patient believes everything is covered. Explain how you would clarify their benefits." },
  quiz: { layoutId: "quiz", icon: "checklist", title: "Knowledge Check", quizQuestion: "What should be confirmed before estimating patient cost?", body: "What should be confirmed before estimating patient cost?", quizChoices: ["Deductible", "Annual maximum", "Waiting period", "All of the above"], bullets: ["Deductible", "Annual maximum", "Waiting period", "All of the above"], correctAnswerIndex: 3, quizExplanation: "All three affect the estimate.", narrationScript: "What should be confirmed before estimating patient cost?" },
  "avatar-intro": { layoutId: "avatar-intro", icon: "video", title: "Welcome to the Lesson", body: "Let’s build confidence with insurance verification.", avatarEnabled: true, avatarScript: "Welcome to the lesson. Let’s build confidence with insurance verification.", narrationScript: "Welcome to the lesson. Let’s build confidence with insurance verification." },
  example: { layoutId: "example", icon: "calculator", title: "Deductible Example", body: "Calculate the estimated patient responsibility.", processSteps: [{ title: "$1,000 fee", description: "Treatment fee", icon: "dollar" }, { title: "$50 deductible", description: "Remaining deductible", icon: "calculator" }, { title: "80% coverage", description: "Plan percentage", icon: "shield" }], bullets: ["$1,000 fee", "$50 deductible", "80% coverage"], exampleResult: "Apply the deductible before calculating plan coverage.", narrationScript: "Apply the deductible before calculating plan coverage." },
  recap: { layoutId: "recap", icon: "checklist", title: "Key Takeaways", body: "Use these checks during every verification.", recapItems: [{ title: "Confirm eligibility", description: "Verify active coverage", icon: "checklist" }, { title: "Check plan limits", description: "Review maximums", icon: "shield" }, { title: "Document details", description: "Record the call", icon: "clipboard" }], bullets: ["Confirm eligibility", "Check plan limits", "Document details"], narrationScript: "Confirm eligibility, check plan limits, and document the details." },
  "avatar-outro": { layoutId: "avatar-outro", icon: "video", title: "Lesson Complete", body: "You’re ready to apply this workflow.", avatarEnabled: true, avatarScript: "You’re ready to apply this workflow with confidence.", narrationScript: "You’re ready to apply this workflow with confidence." },
};

export const assetPreviewLayoutIds = Object.keys(scenes) as Array<keyof typeof scenes>;

export function createAssetPreviewLesson(layoutId: keyof typeof scenes): VideoLessonMetadata {
  return normalizeVideoLesson({ id: `asset_preview_${layoutId}`, title: "Approved Asset Preview", templateId: "revive-academy", renderStatus: "draft", createdAt: "2026-07-18T00:00:00.000Z", updatedAt: "2026-07-18T00:00:00.000Z", scenes: [{ id: `preview_${layoutId}`, durationInSeconds: 6, title: "Preview", body: "", narrationScript: "", ...(scenes[layoutId] as Partial<VideoLessonScene>), layoutId: layoutId as VideoLessonLayoutId }] });
}
