import type { VideoLessonScene } from "../../../lib/video-lessons/videoLessonTypes";
import { videoLessonLayouts, type VideoLessonLayoutId } from "../../../lib/video-lessons/videoLessonLayouts";
import { getLayoutRecommendedUse, validateScene } from "../../../lib/video-lessons/videoLessonSceneEditor";
import { approvedReviveIconNames, getReviveIconName, nativeApprovedReviveIconNames, reviveComponentAssetRegistry, reviveIconRegistry, type ReviveIconName } from "../../../lib/video-lessons/reviveIconRegistry";

type Props = { scene: VideoLessonScene; sceneIndex: number; sceneCount: number; onChange: (patch: Partial<VideoLessonScene>) => void };

function LinesField({ label, value, max, onChange }: { label: string; value?: string[]; max?: number; onChange: (value: string[]) => void }) {
  return <label>{label}<textarea value={(value || []).join("\n")} onChange={(event) => onChange(event.target.value.split("\n").map((item) => item.trim()).filter(Boolean).slice(0, max))} /><span className="vlb-field-hint">One item per line{max ? ` · maximum ${max}` : ""}</span></label>;
}

function IconAssetPicker({ value, layoutId, onChange }: { value?: string; layoutId?: VideoLessonLayoutId; onChange: (value: ReviveIconName) => void }) {
  const selected = getReviveIconName(value, layoutId);
  return <fieldset className="vlb-icon-picker"><legend>Approved icon</legend><div>{approvedReviveIconNames.map((name) => <label key={name} className={selected === name ? "is-selected" : ""}><input type="radio" name="scene-approved-icon" value={name} checked={selected === name} onChange={() => onChange(name)} /><img src={reviveIconRegistry[name]} alt="" /><span>{name}</span></label>)}</div></fieldset>;
}

export function SceneVisualEditor({ scene, sceneIndex, sceneCount, onChange }: Props) {
  const issues = validateScene(scene);
  const setLayout = (layoutId: VideoLessonLayoutId) => onChange({ layoutId });
  return <>
    <div className="vlb-editor-heading"><div><p className="vlb-eyebrow">Scene {sceneIndex + 1} of {sceneCount}</p><h2>{videoLessonLayouts.find((item) => item.id === scene.layoutId)?.name || "Scene"} Editor</h2></div><span className="vlb-autosave-badge">Autosaved</span></div>
    {!!issues.length && <div className="vlb-validation" role="status">{issues.map((issue) => <div key={`${issue.field}-${issue.message}`} className={`is-${issue.severity}`}>{issue.message}</div>)}</div>}
    <div className="vlb-form-grid">
      <label>Layout<select value={scene.layoutId || "definition"} onChange={(event) => setLayout(event.target.value as VideoLessonLayoutId)}>{videoLessonLayouts.map((layout) => <option key={layout.id} value={layout.id}>{layout.name}</option>)}</select></label>
      <label>Scene order<input type="number" value={sceneIndex + 1} readOnly /><span className="vlb-field-hint">Reorder from the scene list.</span></label>
      <label>Scene title<input value={scene.title} onChange={(event) => onChange({ title: event.target.value })} /></label>
      <label>Subtitle<textarea value={scene.subtitle || scene.body} onChange={(event) => onChange({ subtitle: event.target.value, body: event.target.value })} /></label>
      <IconAssetPicker value={scene.icon} layoutId={scene.layoutId} onChange={(icon) => onChange({ icon })} />
      <label>Animation<select value={scene.animationStyle || "rise"} onChange={(event) => onChange({ animationStyle: event.target.value as VideoLessonScene["animationStyle"] })}><option value="rise">Rise</option><option value="fade">Fade</option><option value="pan">Pan</option><option value="wipe">Wipe</option><option value="stagger">Stagger</option></select></label>
      <label>Presentation mode<select value={scene.avatarEnabled ? "avatar" : "voiceover"} onChange={(event) => onChange({ avatarEnabled: event.target.value === "avatar", voiceoverMode: event.target.value as VideoLessonScene["voiceoverMode"] })}><option value="voiceover">Voiceover only</option><option value="avatar">Avatar enabled</option></select></label>
      <label>Duration in seconds<input type="number" min={4} value={scene.durationInSeconds || 8} onChange={(event) => onChange({ durationInSeconds: Number(event.target.value) })} /></label>
    </div>

    {(scene.layoutId === "title" || scene.layoutId === "section-divider") && <div className="vlb-form-grid"><label>Eyebrow label<input value={scene.eyebrow || ""} onChange={(event) => onChange({ eyebrow: event.target.value })} /></label><LinesField label="Highlighted title words" value={scene.highlightedWords} onChange={(highlightedWords) => onChange({ highlightedWords })} /></div>}
    {scene.layoutId === "definition" && <><label>Definition<textarea value={scene.body} onChange={(event) => onChange({ body: event.target.value, subtitle: event.target.value })} /></label><LinesField label="Supporting points" value={scene.bullets} max={3} onChange={(bullets) => onChange({ bullets })} /></>}
    {scene.layoutId === "comparison" && <div className="vlb-two-column-fields"><div><label>Left title<input value={scene.comparisonLeftTitle || ""} onChange={(event) => onChange({ comparisonLeftTitle: event.target.value })} /></label><LinesField label="Left points" value={scene.comparisonLeftPoints} onChange={(comparisonLeftPoints) => onChange({ comparisonLeftPoints })} /></div><div><label>Right title<input value={scene.comparisonRightTitle || ""} onChange={(event) => onChange({ comparisonRightTitle: event.target.value })} /></label><LinesField label="Right points" value={scene.comparisonRightPoints} onChange={(comparisonRightPoints) => onChange({ comparisonRightPoints })} /></div><label>Comparison footer<input value={scene.comparisonFooter || ""} onChange={(event) => onChange({ comparisonFooter: event.target.value })} /></label></div>}
    {scene.layoutId === "process" && <LinesField label="Process steps" value={(scene.processSteps?.length ? scene.processSteps.map((step) => `${step.title} | ${step.description || ""} | ${step.icon || ""}`) : scene.bullets)} max={6} onChange={(rows) => onChange({ processSteps: rows.map((row) => { const [title, description, icon] = row.split("|").map((part) => part.trim()); return { title, description, icon }; }), bullets: rows.map((row) => row.split("|")[0].trim()) })} />}
    {scene.layoutId === "timeline" && <LinesField label="Timeline milestones" value={(scene.timelineMilestones?.length ? scene.timelineMilestones.map((item) => `${item.label} | ${item.duration || ""} | ${item.description || ""}`) : scene.bullets)} max={6} onChange={(rows) => onChange({ timelineMilestones: rows.map((row) => { const [label, duration, description] = row.split("|").map((part) => part.trim()); return { label, duration, description }; }), bullets: rows.map((row) => row.split("|")[0].trim()) })} />}
    {scene.layoutId === "example" && <><LinesField label="Calculation rows" value={scene.exampleRows?.map((row) => `${row.label} | ${row.value}`)} onChange={(rows) => onChange({ exampleRows: rows.map((row) => { const [label, value] = row.split("|").map((part) => part.trim()); return { label, value }; }) })} /><label>Result or takeaway<textarea value={scene.exampleResult || ""} onChange={(event) => onChange({ exampleResult: event.target.value })} /></label></>}
    {scene.layoutId === "patient-scenario" && <div className="vlb-form-grid"><label>Patient quote or situation<textarea value={scene.patientQuote || ""} onChange={(event) => onChange({ patientQuote: event.target.value })} /></label><label>Background details<textarea value={scene.backgroundDetails || scene.body} onChange={(event) => onChange({ backgroundDetails: event.target.value, body: event.target.value })} /></label><label>Discussion prompt<textarea value={scene.discussionPrompt || ""} onChange={(event) => onChange({ discussionPrompt: event.target.value })} /></label><label>Recommended response<textarea value={scene.recommendedResponse || ""} onChange={(event) => onChange({ recommendedResponse: event.target.value })} /></label></div>}
    {scene.layoutId === "quiz" && <><label>Question<textarea value={scene.quizQuestion || scene.body} onChange={(event) => onChange({ quizQuestion: event.target.value, body: event.target.value })} /></label><LinesField label="Answer choices" value={scene.quizChoices?.length ? scene.quizChoices : scene.bullets} max={4} onChange={(quizChoices) => onChange({ quizChoices, bullets: quizChoices })} /><div className="vlb-form-grid"><label>Correct answer<select value={scene.correctAnswerIndex || 0} onChange={(event) => onChange({ correctAnswerIndex: Number(event.target.value) })}>{(scene.quizChoices || scene.bullets || []).map((choice, index) => <option key={`${choice}-${index}`} value={index}>{index + 1}. {choice}</option>)}</select></label><label>Reveal after seconds<input type="number" min={0} value={scene.answerRevealInSeconds ?? 0} onChange={(event) => onChange({ answerRevealInSeconds: Number(event.target.value) })} /></label></div><label>Explanation<textarea value={scene.quizExplanation || ""} onChange={(event) => onChange({ quizExplanation: event.target.value })} /></label></>}
    {scene.layoutId === "recap" && <LinesField label="Takeaway cards" value={scene.recapItems?.length ? scene.recapItems.map((item) => `${item.title} | ${item.description || ""} | ${item.icon || ""}`) : scene.bullets} max={4} onChange={(rows) => onChange({ recapItems: rows.map((row) => { const [title, description, icon] = row.split("|").map((part) => part.trim()); return { title, description, icon }; }), bullets: rows.map((row) => row.split("|")[0].trim()) })} />}
    {(scene.layoutId === "avatar-intro" || scene.layoutId === "avatar-outro" || scene.avatarEnabled) && <div className="vlb-form-grid"><label>Avatar script<textarea value={scene.avatarScript || scene.narrationScript} onChange={(event) => onChange({ avatarScript: event.target.value, narrationScript: event.target.value })} /></label><label>Avatar placement<select value={scene.avatarPlacement || "right"} onChange={(event) => onChange({ avatarPlacement: event.target.value as VideoLessonScene["avatarPlacement"] })}><option value="left">Left</option><option value="right">Right</option><option value="center">Center</option></select></label><div className="vlb-heygen-placeholder">HeyGen status: <strong>{scene.heygenStatus || "idle"}</strong>. Generation remains in the existing advanced media workflow.</div></div>}
    <label>Narration script<textarea className="vlb-narration-field" value={scene.narrationScript} onChange={(event) => onChange({ narrationScript: event.target.value, ...(scene.avatarEnabled ? { avatarScript: event.target.value } : {}) })} /></label>
    <details className="vlb-advanced-options"><summary>Advanced media and background options</summary><div className="vlb-form-grid"><label>Image or media URL<input value={scene.mediaUrl || scene.imageUrl || ""} onChange={(event) => onChange({ mediaUrl: event.target.value, imageUrl: event.target.value })} /></label><label>Background image URL<input value={scene.backgroundImageUrl || ""} onChange={(event) => onChange({ backgroundImageUrl: event.target.value })} /></label><label>Background video URL<input value={scene.backgroundVideoUrl || ""} onChange={(event) => onChange({ backgroundVideoUrl: event.target.value })} /></label><label>Media position<select value={scene.mediaPosition || "right"} onChange={(event) => onChange({ mediaPosition: event.target.value as VideoLessonScene["mediaPosition"] })}><option value="left">Left</option><option value="right">Right</option><option value="center">Center</option><option value="background">Background</option></select></label></div></details>
  </>;
}

export function SceneLibrary({ onAdd, onClose }: { onAdd: (layoutId: VideoLessonLayoutId) => void; onClose: () => void }) {
  return <div className="vlb-modal-backdrop" role="presentation" onMouseDown={onClose}><section className="vlb-scene-library" role="dialog" aria-modal="true" aria-labelledby="scene-library-title" onMouseDown={(event) => event.stopPropagation()}><div className="vlb-panel-title"><div><p className="vlb-eyebrow">Visual scene library</p><h2 id="scene-library-title">Choose a branded layout</h2></div><button type="button" onClick={onClose}>Close</button></div><div className="vlb-layout-library-grid">{videoLessonLayouts.map((layout) => <article key={layout.id} className="vlb-layout-card"><div className={`vlb-layout-thumbnail is-${layout.thumbnail}`}><span /><span /><span /></div><h3>{layout.name}</h3><p>{layout.description}</p><small>{getLayoutRecommendedUse(layout.id)}</small><button type="button" className="vlb-primary" onClick={() => onAdd(layout.id)}>Add Scene</button></article>)}</div></section></div>;
}

export function AssetPreviewPanel({ onClose }: { onClose: () => void }) {
  return <div className="vlb-modal-backdrop" role="presentation" onMouseDown={onClose}><section className="vlb-scene-library vlb-asset-preview" role="dialog" aria-modal="true" aria-labelledby="asset-preview-title" onMouseDown={(event) => event.stopPropagation()}><div className="vlb-panel-title"><div><p className="vlb-eyebrow">Development only</p><h2 id="asset-preview-title">Approved Asset Preview</h2></div><button type="button" onClick={onClose}>Close</button></div><h3>Native SVG icons</h3><div className="vlb-asset-grid">{nativeApprovedReviveIconNames.map((name) => <article key={name}><img src={reviveIconRegistry[name]} alt={`${name} approved icon`} /><strong>{name}</strong><code>scene.icon: "{name}"</code></article>)}</div><h3>Approved component assets</h3><div className="vlb-asset-grid is-components">{Object.entries(reviveComponentAssetRegistry).map(([name, src]) => <article key={name}><img src={src} alt={name} /><strong>{name}</strong></article>)}</div><p className="vlb-field-hint">Reference PNGs are intentionally excluded from renderer controls and remain visual references only.</p></section></div>;
}
